### PR TITLE
Secure and audit Rails console

### PR DESCRIPTION
**Pull request by DerekCrosson**
- Adds code to only allow admin users to access the Rails console.
- Adds code to store audit logs in the database, showing which user modified records.

### CODE REVIEW

**Comment by davidteren** [comment]
Hey @DerekCrosson thanks for the contribution. I'll take a look.
Would you mind running the pre-commit hooks as  (see the Readme) it checks several items one of which is [failing the build](https://github.com/davidteren/sensible_rails_starter/actions/runs/5525169949/jobs/10078672025?pr=243).

**Comment by davidteren** [comment]
@DerekCrosson also let's not include the major Ruby version bump as part of this PR. That should be separate and I need to fix some skipped specs first before bumping it.

**Comment by DerekCrosson** [comment]
> @DerekCrosson also let's not include the major Ruby version bump as part of this PR. That should be separate and I need to fix some skipped specs first before bumping it.

Sure, will get to it sometime this week 🙂

**Comment by davidteren** [comment]
> > @DerekCrosson also let's not include the major Ruby version bump as part of this PR. That should be separate and I need to fix some skipped specs first before bumping it.
> 
> Sure, will get to it sometime this week 🙂

Ignore this. I see it is on Ruby 3.2.2
Not sure why the the Gemfile.lock did not previously update to reflect this.

**Comment by davidteren** [comment]
@DerekCrosson please check the schema file.

**Comment by DerekCrosson** [comment]
> @DerekCrosson please check the schema file.

@davidteren my bad 😁 Forgot to drop the database before making changes, that was from an old side project 🙈 Fixed now.

**Comment by davidteren** [comment]
> > @DerekCrosson please check the schema file.
> 
> @davidteren my bad 😁 Forgot to drop the database before making changes, that was from an old side project 🙈 Fixed now.

All good. PS: I've been meaning to add Organisations and tenants so if you're up to it.

**Comment by DerekCrosson** [comment]
> > > @DerekCrosson please check the schema file.
> > 
> > 
> > @davidteren my bad 😁 Forgot to drop the database before making changes, that was from an old side project 🙈 Fixed now.
> 
> All good. PS: I've been meaning to add Organisations and tenants so if you're up to it.

Happy to work on it! I'll create a PR for it over the weekend 🙂

**Pull request merged**
